Transform: 'AWS::Serverless-2016-10-31'
Resources:

  emailsFunction:
    # This resource creates a Lambda function.
    Type: 'AWS::Serverless::Function'
    
    Properties:
      
      # This function uses the Nodejs v8.10 runtime.
      Runtime: nodejs10.x

      Timeout: 60
        
      # This is the Lambda function's handler.
      Handler: index.handler
      
      # The location of the Lambda function code.
      CodeUri: ./

      Environment:
        Variables:
          gmailCredentials: ${gmailCredentials}
          gmailToken: ${gmailToken}
      
      # Event sources to attach to this function. In this case, we are attaching
      # one API Gateway endpoint to the Lambda function. The function is
      # called when a HTTP request is made to the API Gateway endpoint.
      Events:

        CreateEmailsApi:
            # Define an API Gateway endpoint that responds to HTTP GET at /emails
            Type: Api
            Properties:
                Path: /emails
                Method: POST